package com.jarscan.model;

public enum ProgressPhase {
    PREPARING,
    VALIDATING_UPLOAD,
    EXTRACTING_PROJECT_ZIP,
    DETECTING_PROJECT_STRUCTURE,
    MAVEN_RESOLUTION,
    ANALYZING,
    ANALYZING_PACKAGED_ARTIFACTS,
    INSPECTING_WAR_EAR,
    INSPECTING_FAT_JAR,
    VULNERABILITY_SCAN,
    REPORTING,
    COMPLETED,
    FAILED,
    CANCELLED
}
